# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo My gardle Application
  displayName: 'Run a one-script line'
- script: sh 'gradle build'
  displayName: 'Build with Gradle'
- script: sh 'gradle run'
  displayName: 'Run Application with gradle'
    